#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

auth_success = b"""<?xml version="1.0" encoding="windows-1257"?>\r\n<soap:Envelope xmlns:soap="http://www.w3.org/2001/09/soap-envelope">\r\n<soap:Header xmlns:Lursoft="x-schema:/schemas/lursoft_header.xsd">\r\n<Lursoft:SessionId>8F1D5C6D88DE9F4B2D9F159A32656FA2</Lursoft:SessionId>\r\n<Lursoft:Language>LV</Lursoft:Language>\r\n<Lursoft:IP>159.148.5.233</Lursoft:IP>\r\n<Lursoft:Time>2016-12-01T16:54:43</Lursoft:Time>\r\n<Lursoft:UserId>in225854</Lursoft:UserId>\r\n<Lursoft:Distributor>www.lursoft.lv</Lursoft:Distributor>\r\n</soap:Header>\r\n</soap:Envelope>\r\n"""

query_fail_login = b"""<?xml version="1.0" encoding="windows-1257"?>\r\n<soap:Envelope xmlns:soap="http://www.w3.org/2001/09/soap-envelope" xmlns:Lursoft="x-schema:/schemas/lursoft_header.xsd">\r\n<soap:Header xmlns:Lursoft="x-schema:/schemas/lursoft_header.xsd">\r\n<Lursoft:SessionId>36787CD5EFF6B0AE3989F2335B3D9697</Lursoft:SessionId>\r\n<Lursoft:Language>LV</Lursoft:Language>\r\n<Lursoft:IP>159.148.5.233</Lursoft:IP>\r\n<Lursoft:Time>2016-12-01T17:43:36</Lursoft:Time>\r\n<Lursoft:Distributor>www.lursoft.lv</Lursoft:Distributor>\r\n</soap:Header>\r\n<soap:Body>\r\n<Fault>\r\n<Faultcode>soap:Client</Faultcode>\r\n<Faultstring>Request processing error</Faultstring>\r\n<details>\r\n<Lursoft:ErrorCode>7</Lursoft:ErrorCode>\r\n<Lursoft:ErrorMsg>L\xfbdzu, ievadiet lietot\xe2ja ID un paroli.</Lursoft:ErrorMsg>\r\n</details>\r\n</Fault>\r\n</soap:Body>\r\n</soap:Envelope>\r\n"""

success_query = '<?xml version="1.0" encoding="utf-8"?> <soap:Envelope xmlns:soap="http://www.w3.org/2001/09/soap-envelope"> <soap:Header xmlns:Lursoft="x-schema:/schemas/lursoft_header.xsd"> <Lursoft:SessionId>9440248439616E7CF04D42DF660637C4</Lursoft:SessionId> <Lursoft:Language>LV</Lursoft:Language> <Lursoft:IP>159.148.5.233</Lursoft:IP> <Lursoft:Time>2016-12-01T17:59:16</Lursoft:Time> <Lursoft:UserId>in225854</Lursoft:UserId> <Lursoft:Distributor>www.lursoft.lv</Lursoft:Distributor> </soap:Header> <soap:Body> <answer> <source>www.lursoft.lv,www.ur.gov.lv</source> <country>LV</country> <search_code>42103023739</search_code> <person> <regcode>42103023739</regcode> <code>210302373</code> <sepacode>LV74ZZZ42103023739</sepacode> <pvncode>LV42103023739</pvncode> <pvnStatus>active</pvnStatus> <name>SIA &quot;M.DZ.NASKIS&quot;</name> <registered>2000-05-30</registered> <firm>M.DZ.NASKIS</firm> <fname>SIA</fname> <type>SIA</type> <register>K</register> <statuss>1</statuss> <address> <adress_full>Liepaja, Kursu iela 2</adress_full> <city>Liepaja</city> <street>Kursu iela</street> <house>2</house> <index>3401</index> </address> <kmdb>Nav</kmdb> <capitals> <capital> <cap_type>REG</cap_type> <cap_val>2840</cap_val> <currency>EUR</currency> </capital> <capital> <cap_type>APM</cap_type> <cap_val>2840</cap_val> <currency>EUR</currency> </capital> </capitals> </person> <price> <sum>0.14</sum> <currency>EUR</currency> </price> <copyright>(c) LURSOFT 1997-2016, www.lursoft.lv</copyright> </answer> </soap:Body> </soap:Envelope> '
